files:
  # Path to the Panorama configuration XML file to be translated.
  # This path is relative to the project root directory and compatible with both Windows and Linux.
  xml_source_file: "C:/Users/rober/Downloads/10-14-2025.xml"
template:
  tenant: RobK
  description: Template for PAN to Versa Configuration Translation

  # Determines whether to create a single service template or individual templates per device group.
  # - True: Creates a single service template.
  # - False: Creates individual service templates for each device group.
  single_template: False

  # Name of the single service template to be created.
  # Relevant only if `single_template` is set to True.
  single_template_name: Deleteme
 
 
  # How to create the service_template_name_format:
  # 
  # 1. Use the placeholders below to define your format:
  #    - {prefix}: A prefix string you define.
  #    - {device_group_name}: The name of the device group.
  #    - {device_name}: The name of the device.
  #    - {postfix}: A postfix string you define.
  #
  # 2. Combine placeholders with letters (a-z, A-Z), numbers (0-9), and underscores (_).
  #
  # Example:
  # service_template_name_format: "{prefix}_{device_group_name}.{device_name}_{postfix}"
  # This example creates names like: DG_DeviceGroup1.Device1_Config
  #
  # Define your prefix and postfix below:
  service_template_name_format: "{prefix}-{device_name}-{device_group_name}"
  prefix: Deleteme
  postfix: Post
  
  # Determines whether to create a separate shared template.
  # - True: Creates a shared template.
  # - False: Copies objects from the shared template to each service group.
  # Note: Ignored if `single_template` is True.
  create_separate_shared_template: True  

logging:
  # Logging level for console output. Common levels: DEBUG, INFO, WARNING, ERROR, CRITICAL.
  console_level: INFO

  # Logging level for file output. Common levels: DEBUG, INFO, WARNING, ERROR, CRITICAL.
  file_level: DEBUG

upload:
  # Number of requests per second that the Versa Director can handle.
  # Recommended value: 20
  requests_per_second: 75

  # Number of parallel requests that can be sent.
  # No recommended value, but tested up to 100.
  batch_size: 200

parsers:
  address: true
  address_group: true
  application: true
  application_filter: true
  application_group: true
  interface: true
  rules: true
  schedule: true
  service: true
  service_group: true
  zone: true
  dos_rules: true
  profiles:
    enabled: True
    types:
      antivirus: true
      url-filtering: false
      vulnerability: false      # vulnerability profiles are not supported at this time.
      file-blocking: false      # file-blocking profiles are not supported at this time.
      wildfire-analysis: false  # wildfire-analysis profiles are not supported at this time.
      data-filtering: false     # data-filtering profiles are not supported at this time.
      dos: True
      spyware: false            # spyware profiles are not supported at this time.
      sctp-protection: false    # sctp-protection profiles are not supported at this time.
      mobile-security: false    # mobile-security profiles are not supported at this time.
      decryption: false         # decryption profiles are not supported at this time.
      dns-security: false       # dns-security profiles are not supported at this time.
      pcap: false               # pcap profiles are not supported at this time.
      ips: false                # ips profiles are not supported at this time.

transformers:
  # Removes duplicate objects during the transformation process.
  remove_duplicates: true
  
  address: true
  address_group: true
  application: true
  application_filter: true
  application_group: true
  interface: true
  rules: true
  schedule: true
  service: true
  service_group: false          # Service groups are not supported by Versa at this time.
  zone: true
  dos-rules: true
  profiles:
    enabled: true
    types:
      antivirus: true
      url-filtering: false      # url-filtering profiles are not supported at this time.
      vulnerability: false      # vulnerability profiles are not supported at this time.
      file-blocking: false      # file-blocking profiles are not supported at this time.
      wildfire-analysis: false  # wildfire-analysis profiles are not supported at this time.
      data-filtering: false     # data-filtering profiles are not supported at this time.
      dos: false                # dos profiles are not supported at this time. 
      spyware: false            # spyware profiles are not supported at this time.
      sctp-protection: false    # sctp-protection profiles are not supported at this time.
      mobile-security: false    # mobile-security profiles are not supported at this time.
      decryption: false         # decryption profiles are not supported at this time.
      dns-security: false       # dns-security profiles are not supported at this time.
      pcap: false               # pcap profiles are not supported at this time.
      ips: false                # ips profiles are not supported at this time.

uploaders:
  address: true
  address_group: true
  application: true
  application_filter: true
  application_group: true
  interface: False              # !!Unable to create interfaces in next gen firewall service template!!
  rules: true                   # Firewall security rules
  schedule: true
  service: true                 # Turn off for testing
  service_group: false          # Service groups are not supported by Versa at this time.
  zone: true
  dos_rules: true
  profiles:
    enabled: false
    types:
      antivirus: false          # Antivirus profiles are not supported at this time.
      url-filtering: true       
      vulnerability: false      # vulnerability profiles are not supported at this time.
      file-blocking: false      # file-blocking profiles are not supported at this time.
      wildfire-analysis: false  # wildfire-analysis profiles are not supported at this time.
      data-filtering: false     # data-filtering profiles are not supported at this time.
      dos: true
      spyware: false            # spyware profiles are not supported at this time.
      sctp-protection: false    # sctp-protection profiles are not supported at this time.
      mobile-security: false    # mobile-security profiles are not supported at this time.
      decryption: false         # decryption profiles are not supported at this time. 
      dns-security: false       # dns-security profiles are not supported at this time.
      pcap: false               # pcap profiles are not supported at this time.
      ips: false                # ips profiles are not supported at this time.

defaults:
  # Default risk level (scale: 1-5).
  risk: 3

  # Determines whether to match application IPs by default.
  app-match-ips: false

  # Default productivity setting (scale: 1-5).
  productivity: 3

api_endpoints:
  # OAuth token endpoint.
  oauth: "/auth/token"

  # Base API path for device template configurations.
  # Placeholders:
  # - {template_name}: Name of the template.
  # - {tenant}: Tenant identifier.
  base_path: "api/config/devices/template/{template_name}/config/orgs/org-services/{tenant}"

  # Endpoint for service templates.
  service_template: "/vnms/template/serviceTemplate"

  # Paths for various object types within the API.
  object_path:
    address: "objects/addresses"
    address_group: "objects/address-groups"
    service: "objects/services" 
    application: "application-identification/user-defined-applications"
    application_group: "application-identification/application-groups"
    application_filter: "application-identification/application-filters"
    rules: "security/access-policies/access-policy-group/Default-Policy/rules"
    interface: "network/interfaces"
    zone: "objects/zones"
    schedule: "objects/schedules"
    dos_rules: security/dos-policies/dos-policy-group/Default-Policy/rules
    profiles:
        antivirus: "security/profiles/antivirus"
        #data-filtering: "security/profiles/data-filtering"
        decryption: "security/profiles/decryption"
        #dns-security: "security/profiles/dns-security"
        dos:
          aggregate: "security/profiles/dos/aggregate"
          classified: "security/profiles/dos/classified"
        file-blocking: "security/profiles/file-blocking"
        file-filtering: "security/profiles/file-filtering"
        ips: "security/profiles/ips"
        #mobile-security:
        #pcap:
        #sctp-protection:
        #spyware:
        url-filtering: "security/profiles/url-filtering"
        vulnerability: "security/profiles/ips"
        #wildfire-analysis: 

token:
  # Token expiry time in seconds.
  expiry: 3600

  # Enables or disables token refresh functionality.
  refresh_enabled: true

  # Endpoint URL for refreshing tokens.
  refresh_url: "/auth/refresh"