files:
  # Path to the Panorama configuration XML file to be translated.
  # This path is relative to the project root directory and compatible with both Windows and Linux.
  xml_source_file: "./Source_Files/Panorama_Config_8-30-23 - Copy.xml"

template:
  tenant: RobK
  description: Template for PAN to Versa Configuration Translation

  # Determines whether to create a single service template or individual templates per device group.
  # - True: Creates a single service template.
  # - False: Creates individual service templates for each device group.
  single_template: False

  # Name of the single service template to be created.
  # Relevant only if `single_template` is set to True.
  single_template_name: Deleteme
 
 
  # How to create the service_template_name_format:
  # 
  # 1. Use the placeholders below to define your format:
  #    - {prefix}: A prefix string you define.
  #    - {device_group_name}: The name of the device group.
  #    - {device_name}: The name of the device.
  #    - {postfix}: A postfix string you define.
  #
  # 2. Combine placeholders with letters (a-z, A-Z), numbers (0-9), and underscores (_).
  #
  # Example:
  # service_template_name_format: "{prefix}_{device_group_name}.{device_name}_{postfix}"
  # This example creates names like: DG_DeviceGroup1.Device1_Config
  #
  # Define your prefix and postfix below:
  service_template_name_format: "{prefix}_{device_name}.{device_group_name}"
  prefix: Deleteme
  postfix: Post
  
  # Determines whether to create a separate shared template.
  # - True: Creates a shared template.
  # - False: Copies objects from the shared template to each service group.
  # Note: Ignored if `single_template` is True.
  create_separate_shared_template: True  

logging:
  # Logging level for console output. Common levels: DEBUG, INFO, WARNING, ERROR, CRITICAL.
  console_level: INFO

  # Logging level for file output. Common levels: DEBUG, INFO, WARNING, ERROR, CRITICAL.
  file_level: DEBUG

upload:
  # Number of requests per second that the Versa Director can handle.
  # Recommended value: 20
  requests_per_second: 30

  # Number of parallel requests that can be sent.
  # No recommended value, but tested up to 100.
  batch_size: 100

api_endpoints:
  # OAuth token endpoint.
  oauth: "/auth/token"

  # Base API path for device template configurations.
  # Placeholders:
  # - {template_name}: Name of the template.
  # - {tenant}: Tenant identifier.
  base_path: "api/config/devices/template/{template_name}/config/orgs/org-services/{tenant}"

  # Endpoint for service templates.
  service_template: "/vnms/template/serviceTemplate"

  # Paths for various object types within the API.
  object_path:
    address: "objects/addresses"
    address_group: "objects/address-groups"
    service: "objects/services" 
    application: "application-identification/user-defined-applications"
    application_group: "application-identification/application-groups"
    application_filter: "application-identification/application-filters"
    rules: "security/access-policies/access-policy-group/Default-Policy/rules"
    zone: "objects/zones"
    schedule: "objects/schedules"
    profile.antivirus: "security/profiles/av"
    profile.dos-classified: "security/profiles/dos/classified"
    profile.dos-aggregate: "security/profiles/dos/aggregate"
    profile.decryption: "security/profiles/decryption"
    profile.file-blocking: "security/profiles/file-filtering"
    profile.ips: "security/profiles/ips"
    profile.url-filtering: "security/profiles/url-filtering"
    profile.vulnerability: security/profiles/"ips"

token:
  # Token expiry time in seconds.
  expiry: 3600

  # Enables or disables token refresh functionality.
  refresh_enabled: true

  # Endpoint URL for refreshing tokens.
  refresh_url: "/auth/refresh"

uploaders:
  address: true
  address_group: true
  application: true
  application_filter: true
  application_group: true
  rules: true
  schedule: true
  service: true
  service_group: false  # Service groups are not supported at this time.
  zone: true
  profiles:
    enabled: false
    types:
      antivirus: true
      url-filtering: true
      vulnerability: true
      file-blocking: true
      wildfire-analysis: true
      data-filtering: true
      dos: true
      spyware: true
      sctp-protection: true
      mobile-security: true
      decryption: true
      dns-security: true
      pcap: true
      ips: true

# The following parsers are not currently in use but may be implemented in future updates.
parsers:
  address: true
  address_group: true
  application: true
  application_filter: true
  application_group: true
  rules: true
  schedule: true
  service: true
  service_group: true
  zones: true
  profile.antivirus: false
  profile.dos-classified: false
  profile.dos-aggregate: false
  profile.decryption: false
  profile.file-blocking: false
  profile.ips: false
  profile.url-filtering: false 
  profile.vulnerability: false

transformers:
  # Removes duplicate objects during the transformation process.
  remove_duplicates: true

  # Removes objects with duplicate names. Set to false to retain all names.
  remove_duplicate_names: true

defaults:
  # Default risk level (scale: 1-5).
  risk: 3

  # Determines whether to match application IPs by default.
  app-match-ips: false

  # Default productivity setting (scale: 1-5).
  productivity: 3
