# General settings
debug: true  # set to True to enable useful console output

# Network related constants
timeout_seconds: 30
rate_limit_wait_increase: 10
network_error_wait: 30

# DOS attack constants
icmp_flood_range_start: 20
icmp_flood_range_end: 220
default_sctp_port: 7654

# Display formatting constants
separator_width: 92
separator_char: ~

# Byte conversion constants
binary_unit_base: 1024.0
decimal_unit_base: 1000.0

# Request settings
min_depth: 3  # minimum click depth
max_depth: 10  # maximum click depth
min_wait: 20  # minimum amount of time allowed between HTTP requests
max_wait: 30  # maximum amount of time to wait between HTTP requests

# Must use a valid user agent or sites will hate you
user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

web_testing:
  enabled: true # set to True to create web traffic

# Denial of service settings
dos_testing:
  enabled: true  # set to True to create DOS traffic
  frequency: 10  # Create DOS traffic every X times
  target:
    dst_ip: "192.168.1.1"  # Enter Target/Destination IP Address with Subnet
    dst_port: "444"  # Enter TCP Destination Port
    duration_sec: 30  # Enter time duration (in sec) for which traffic is to be generated
    source_address: "192.168.0.1"  # Enter Source IP Address for spoofing traffic
  # Comment out profile you do not want to run
  profiles:
    - "TCP Scan"
    - "UDP Scan"
    - "HostSweep Flood"
    - "TCP Flood"
    - "UDP Flood"
    - "ICMP Flood"
    - "SCTP Flood"
    - "Other-IP Flood"
    - "ICMP Fragmention"
    - "ICMP Ping Zero ID"
    - "Non-SYN TCP"
    - "IP Spoofing"
    - "IP Fragmention"
    - "Record-Route"
    - "Strict-SRC-Routing"
    - "Loose-SRC-Routing"
    - "Timestamp"

# URLs for testing
urls:
  # URLs that match to a specific rule
  rule_specific:
    # TG-DNS-Allow (Allow) #Allows access to DNS. No specific URL
    dns_allow:
      - "https://192.168.1.100:389"  # Allows access to port 389 & 636
      - "https://192.168.1.100:636"
    
    # TG-Run-IP-Filter-Profile(Deny) (Please place these app/url into TG-Bad-Events Address Group)
    ip_filter:
      - "https://58.96.82.68"
      - "https://103.240.252.59"
      - "https://103.43.140.104"
      - "https://103.48.139.139"
      - "https://119.41.206.123"
      - "https://15.204.168.1"
      - "https://157.245.201.168"
      - "https://163.123.143.173"
      - "https://193.42.33.70"
      - "https://2.56.58.81"
      - "https://2.56.58.85"
      - "https://2.56.58.88"
      - "https://2.56.58.93"
      - "https://210.140.43.55"
      - "https://219.117.221.11"
      - "https://223.73.35.54"
      - "https://43.131.61.151"
      - "https://43.134.111.101"
      - "https://43.153.135.112"
      - "https://43.163.198.174"
      - "https://45.116.226.132"
      - "https://45.116.226.134"
      - "https://45.116.226.137"
      - "https://45.116.226.138"
      - "https://45.117.140.211"
      - "https://94.205.22.95"
      - "https://103.48.139.91"

    # TG-Run-DNS-Filter-Profile (Block) (Please place these app/url into Security Polices rule TG-Run-DNS-Filter-Profile)
    dns_filter:
      - "https://gitlab.com/"
      - "https://www.deezer.com/us/"

    # TG-Run-AV-Profile (Recommended Action) (Please place these app/url into Security Polices rule TG-Run-AV-Profile)
    av_profile:
      - "https://www.eicar.org/download-anti-malware-testfile/"
      - "https://secure.eicar.org/eicar_com.zip"
      - "http://http-evader.semantic-gap.de/-BGJhmNoDFOy1TQD0tk0P96wLE-2pTBXgrg=="

    # TG-Run-File-Filter-Profile (Block) (Please place these app/url into Security Polices rule TG-Run-File-Filter-Profile)
    file_filter:
      - "https://github.com/nmmapper/python3-nmap/archive/refs/heads/master.zip"
      - "https://github.com/nmmapper/python3-nmap/tree/0e3d16637ff2a3f8aa2e10ab7c4255685946e8c5/nmap3"
      - "https://github.com/versa-networks/libcli/archive/refs/heads/stable.zip"
      - "https://versanetworks.box.com/s/e8p1bxvil4xxbjdh8ardv7l5ame85n5c"

    # TG-Run-Vulnerability-Profile (Please place these app/url into Security Polices rule TG-Run-Vulnerability-Profile)
    vulnerability:
      - "http://http-evader.semantic-gap.de/"
      - "http://http-evader.semantic-gap.de/#xhr_eicar"
      - "http://http-evader.semantic-gap.de/#xhr_novirus"
      - "http://http-evader.semantic-gap.de/#js"
      - "http://37.221.199.196"
      - "http://http-evader.semantic-gap.de/-BGJhmNoDFOy1TQD0tk0P96wLE-2pTBXgrg=="
      - "http://testmyids.com/"

    # TG-Run-ATP-Profile (Please place these app/url into Security Polices rule TG-Run-ATP-Profile)
    atp:
      - "https://secure.eicar.org/eicar.com.txt"

    # TG-Run-CASB-Profile (Please place these app/url into Security Polices rule TG-Run-CASB-Profile)
    casb:
      - "https://reddit.com/"

    # TG-QUIC (Deny) #Denies access to UDP on port 80 and 443
    quic:
      - "https://www.facebook.com"
      - "https://www.google.com"

    # TG-Allow-Business-App-Filters (Allow) #Allows access to AWS, Facebook, Google-Earth
    business_apps:
      - "https://www.aws.amazon.com/"
      - "https://www.facebook.com"
      - "https://earth.google.com"

    # TG-Deny-Non-Business-App-Filters (Deny) #Denies access to Amazon-Apps, Social-Media, Facebook, Sharepoint_Online connection on 80 or 443
    non_business_apps:
      amazon:
        - "https://www.aws.amazon.com/console/"
        - "https://app.chime.aws/meetings"
        - "https://www.primevideo.com/"
        - "https://music.amazon.in/"
      social_media:
        - "https://www.facebook.com"
        - "https://tinder.com"
        - "http://www.orkut.com/"
      non_business:
        - "https://www.01net.com"
        - "https://baidu.com"
        - "https://www.bitlord.com"
        - "https://www.cartoonnetwork.com"
      # High Risk Apps
      high_risk:
        - "https://www.brightcove.com"
        - "https://www.2shared.com/"
        - "https://www.4tube.com/"
        - "https://www.gigatribe.com/"

  # URLS of specific Reputation
  reputation:
    # Trustworthy (Allow)
    trustworthy:
      - "https://cricbuzz.com"
    # Moderate risk (Alert)
    moderate_risk:
      - "https://adform.com"
    # Suspicious (Block)
    suspicious:
      - "https://www.prochoiceamerica.org/"
    # High-Risk (Block)
    high_risk:
      - "http://www.proxify.com/"

  categories:
    business:
      - "https://www.office.com/launch/powerpoint"
      - "https://versanetworks.sharepoint.com/"
      - "https://outlook.office.com/mail/inbox"
      - "https://www.office.com/launch/excel"
      - "https://teams.microsoft.com/"
      - "https://www.mcafee.com/en-in/index.html"
      - "https://www.webex.com/"
      - "https://adobe.com"
    # Shopping URLS (Ask)
    shopping:
      - "https://www.amazon.com"
      - "https://www.flipkart.com"
      - "https://www.myntra.com"
    # Social Media URLS (Justify)
    social_media:
      - "https://www.facebook.com"
      - "https://www.instagram.com"
      - "https://www.twitter.com"
      - "https://www.whatsapp.com"
      - "https://telegram.org"
    # Job Search URLS (Allow)
    job_search:
      - "https://www.linkedin.com"
      - "https://www.naukri.com"
      - "https://www.monster.com"
    google_apps:
      - "https://www.gmail.com"
      - "https://drive.google.com"
      - "https://analytics.google.com/analytics/web/"
    web_browsing:
      - "https://www.mail2000.co"
      - "https://mail.ru/"
      - "https://www.anz.com.au"
    auction:
      - "https://www.ebay.com"
    dating:
      - "https://www.match.com"
    gambling:
      - "https://www.bet365.com"
    proxy:
      - "https://www.kproxy.com"
    weapons:
      - "https://www.grabagun.com"
    adult:
      - "https://www.playboy.com"
    malware:
      - "https://astalavista.box.sk"

  # URLS to browse, may not match to specific rule
  general:
    - "https://digg.com/"
    - "https://www.yahoo.com"
    - "https://www.reddit.com"
    - "http://www.cnn.com"
    - "http://www.ebay.com"
    - "https://en.wikipedia.org/wiki/Main_Page"
    - "https://austin.craigslist.org/"
    - "https://www.flipkart.com"
    - "https://www.facebook.com/games/"
    - "https://www.whatsapp.com"
    - "https://www.instagram.com"
    - "https://www.bittorrent.com"
    - "https://www.kproxy.com"
    - "https://www.ndtv.com"
    - "https://www.youtube.com"
    - "https://www.netflix.com"
    - "https://versanetworks.sharepoint.com/"
    - "https://www.office.com/launch/powerpoint"
    - "https://outlook.office.com/mail/inbox"
    - "https://www.office.com/launch/excel"
    - "https://teams.microsoft.com/"
    - "https://groups.google.com/my-groups"

# List of items to not follow
# Items can be a URL "https://t.co" or simple string to check for "amazon"
ignore_patterns:
  - "https://t.co"
  - "t.umblr.com"
  - "messenger.com" 
  - "itunes.apple.com"
  - "l.facebook.com"
  - "bit.ly"
  - "mediawiki"
  - ".css"
  - ".ico"
  - ".xml"
  - "intent/tweet"
  - "twitter.com/share"
  - "signup"
  - "login"
  - "dialog/feed?"
  - ".png"
  - ".jpg"
  - ".json"
  - ".svg"
  - ".gif"
  - "zendesk"
  - "clickserve"